config/routes.rb
Rails.application.routes.draw do
  resources :groups
  get '/', to: 'welcome#index'

  get 'welcome/index', to: 'welcome#index'
  post 'welcome/index', to: 'welcome#cucumber'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
	validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
 	def index
    @groups = Group.all
  end

  def new
    @group = Group.new
  end

  def show
    @group = Group.find(params[:id])
  end

  def edit
    @group = Group.find(params[:id])
  end

 	def create
	  @group = Group.new(group_params)
    if @group.save
      redirect_to groups_path
    else
      render :new
    end
	end

	def update
	  @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to groups_path, notice: "Update Success"
    else
      render :edit
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    flash[:alert] = "Group deleted"
    redirect_to groups_path
  end

  private

  def group_params
    params.require(:group).permit(:title, :description)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	include FridaystepHelper
	def index
	end

	# POST /test
	def cucumber
    # is_it_friday = FridayStepHelper.new

    @today = params[:cucumber]
    @answer = is_it_friday(@today)
	  Rails.logger.debug("today: #{params[:cucumber]}")
	  Rails.logger.debug("today: #{@today}")
	  # Rails.logger.debug("answer: #{@answer}")
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fridaystep_helper.rb
module FridaystepHelper
  def is_it_friday(day)
    if day == 'Friday'
      'Yes!!!'
    else
      "呵呵不是唷！！！"
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
    <p class="text-center">©2018 Asgard Cucumber
        <br>Design by
        <a href="http://courses.growthschool.com/courses/rails-101/" target=_new>NeoYin</a>
    </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="/">Cucumber Home</a>
            <a class="navbar-brand" href="/groups">Group</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <!-- <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <%= link_to("Login", '#') %>
                </li>
            </ul>
        </div> -->
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/groups/_form.html.erb
<%= simple_form_for @group do |f| %>
  <div class="form-group">
    <%= f.input :title, input_html: { class: "form-control"} %>
    <%= f.input :description, input_html: { class: "form-control"} %>
  </div>
  <%= f.submit "Submit", class: "btn btn-primary", data: { disable_with: "Submitting..." } %>
<% end %>

app/views/groups/edit.html.erb
<div class="col-md-4 col-md-offset-4">
  <h2>Edit Group</h2>
  <hr>
  <%= render "form" %>
</div>

app/views/groups/index.html.erb
<div class="col-md-12">
  <div class="group">
    <%= link_to("New group", new_group_path, class: "btn btn-primary pull-right") %>
  </div>
  <table class="table table-hover">
    <thead>
      <tr>
        <td>#</td>
        <td>Title</td>
        <td>Description</td>
      </tr>
    </thead>
    <tbody>
      <% @groups.each do |group| %>
        <tr>
          <td>#</td>
          <td><%= link_to(group.title, group_path(group)) %></td>
          <td><%= group.description %></td>
          <td>
              <%= link_to("Edit", edit_group_path(group), class: "btn btn-sm btn-default")%>
              <%= link_to("Delete", group_path(group),    class: "btn btn-sm btn-default", 
                          method: :delete, data: { confirm: "Are you sure?" } )%>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/groups/new.html.erb
<div class="col-md-4 col-md-offset-4">
  <h2>New group</h2>
  <hr>
  <%= render "form" %>
</div>

app/views/groups/show.html.erb
<div class="col-md-12">
  <div class="group">
    <%= link_to("Edit", edit_group_path(@group), class: "btn btn-primary pull-right")%>
  </div>
  <h2><%= @group.title %></h2>
  <p><%= @group.description %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cucumber</title>
    <%= csrf_meta_tags %>
    <!-- <%= csp_meta_tag %> -->

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
        <div class="container-fluid">
            <%= render "common/navbar" %>
            <%= yield %>
        </div>
        <%= render "common/footer" %>
    </body>
</html>

app/views/welcome/cucumber.html.erb
<p>Your input is</p>
<%= @today %>
<p>Answer is</p>
<%= @answer %>

app/views/welcome/index.html.erb
<h1> NeoYin cucumber test :) </h1>

<%= form_tag('/welcome/index') do |form| %>
  <p>Is it Friday yet?</p>
  <%= text_area_tag 'cucumber' %>
  <%= submit_tag "submit" %>
<% end %>

<p>answer is</p>
<p></p>